name: OWASP Juice Shop CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: bkimminich/juice-shop
  IMAGE_TAG: latest
  # AWS_REGION: us-east-1 # Change this to your AWS region

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Run container for testing
        run: |
          docker run -d -p 3000:3000 --name juice-shop ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          sleep 10 # Wait for container to start

      - name: Basic health check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ $response -eq 200 ]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi

      - name: Stop container
        run: docker stop juice-shop && docker rm juice-shop
